const skills = [
  {
    id: 1,
    title: 'HTML',
    subtitle: "HTML é uma linguagem de marcação utilizada na construção de páginas na Web.",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/html.png?raw=true",
    category: 'front',
  },
  {
    id: 2,
    title: 'CSS',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/css.png?raw=true",
    category: 'front',
  },
  {
    id: 3,
    title: 'JS',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/js.png?raw=true",
    category: 'front',
  },
  {
    id: 4,
    title: 'React',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/react.png?raw=true",
    category: 'front',
  },
  {
    id: 5,
    title: 'Redux',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/redux.png?raw=true",
    category: 'front',
  },
  {
    id: 6,
    title: 'Context',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/context.png?raw=true",
    category: 'front',
  },
  {
    id: 7,
    title: 'Styled C.',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/styled.png?raw=true",
    category: 'front',
  },
  {
    id: 8,
    title: 'Jest',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://raw.githubusercontent.com/kelvynkhrystian/portifolio/6d10f3e63f0443af570bf510386634ff4c5a0438/src/imgs/skills/jest.svg",
    category: 'front',
  },
  {
    id: 9,
    title: 'RTL',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/rtl.png?raw=true",
    category: 'front',
  },
  {
    id: 10,
    title: 'Node',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/node.png?raw=true",
    category: 'back',
  },
  {
    id: 11,
    title: 'MySql',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/mysql.png?raw=true",
    category: 'back',
  },
  {
    id: 12,
    title: 'Express',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/exp.png?raw=true",
    category: 'back',
  },
  {
    id: 13,
    title: 'Sequelize',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/sequelize.png?raw=true",
    category: 'back',
  },
  {
    id: 14,
    title: 'JWT',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://raw.githubusercontent.com/kelvynkhrystian/portifolio/8adbb4d1c4c9bb82c85f3bed6454bb3ebf583eb1/src/imgs/skills/jwt.svg",
    category: 'back',
  },
  {
    id: 15,
    title: 'Chai',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/chai.png?raw=true",
    category: 'back',
  },
  {
    id: 16,
    title: 'Mocha',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/mocha.png?raw=true",
    category: 'back',
  },
  {
    id: 17,
    title: 'Sinon',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/sinon.png?raw=true",
    category: 'back',
  },
  {
    id: 18,
    title: 'Linux',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/linux.png?raw=true",
    category: 'ferr',
  },
  {
    id: 19,
    title: 'Git',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/git.png?raw=true",
    category: 'ferr',
  },
  {
    id: 20,
    title: 'Docker',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/docker.png?raw=true",
    category: 'ferr',
  },
  {
    id: 21,
    title: 'Vercel',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/vercel.jpg?raw=true",
    category: 'ferr',
  },
  {
    id: 22,
    title: 'Trello',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/trello.png?raw=true",
    category: 'ferr',
  },
  {
    id: 23,
    title: 'Slack',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/slack.png?raw=true",
    category: 'ferr',
  },
  {
    id: 24,
    title: 'Figma',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/figma.png?raw=true",
    category: 'ferr',
  }
  
]

export default skills;