const skills = [
  {
    id: '1',
    title: 'HTML',
    subtitle: "HTML é uma linguagem de marcação utilizada na construção de páginas na Web.",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/html.png?raw=true",
    category: 'front',
    description: 'HTML (Linguagem de Marcação de HiperTexto) é o bloco de construção mais básico da web. Define o significado e a estrutura do conteúdo da web. ',
  },
  {
    id: '2',
    title: 'CSS',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/css.png?raw=true",
    category: 'front',
    description: "CSS (Cascading Style Sheets ou Folhas de Estilo em Cascata) é uma linguagem de estilo usada para descrever a apresentação de um documento escrito em HTML ou em XML.",
  },
  {
    id: '3',
    title: 'JS',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/js.png?raw=true",
    category: 'front',
    description: 'JavaScript® (às vezes abreviado para JS) é uma linguagem leve, interpretada e baseada em objetos com funções de primeira classe, mais conhecida como a linguagem de script para páginas Web, mas usada também em vários outros ambientes sem browser, tais como node.js, Apache CouchDB e Adobe Acrobat. ',
  },
  {
    id: '4',
    title: 'React',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/react.png?raw=true",
    category: 'front',
    description: 'O React é uma biblioteca front-end JavaScript de código aberto com foco em criar interfaces de usuário em páginas web.',
  },
  {
    id: '5',
    title: 'Redux',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/redux.png?raw=true",
    category: 'front',
    description: 'Redux é uma biblioteca JavaScript de código aberto para gerenciar o estado do aplicativo. É mais comumente usado com bibliotecas como React ou Angular para criar interfaces de usuário. ',
  },
  {
    id: '6',
    title: 'Context',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/context.png?raw=true",
    category: 'front',
    description: 'O React context API é um gerenciador de estado global e é uma funcionalidade implementada a pouco tempo no ecossistema do React, podendo resolver 90% das soluções do Redux de forma extremamente simples.',
  },
  {
    id: '7',
    title: 'Styled C.',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/styled.png?raw=true",
    category: 'front',
    description: 'O Styled Components é uma biblioteca (lib) do React e do React Native que nos permite criar componentes de estilo ao escrever códigos CSS dentro de um arquivo JavaScript.',
  },
  {
    id: '8',
    title: 'Jest',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://raw.githubusercontent.com/kelvynkhrystian/portifolio/6d10f3e63f0443af570bf510386634ff4c5a0438/src/imgs/skills/jest.svg",
    category: 'front',
    description: 'Jest é uma estrutura de teste de JavaScript construída sobre o Jasmine e mantida pela Meta. Ele foi projetado e construído por Christoph Nakazawa com foco na simplicidade e suporte para grandes aplicativos da web. ',
  },
  {
    id: '9',
    title: 'RTL',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/rtl.png?raw=true",
    category: 'front',
    description: 'React Testing Library é um conjunto de utilitários que permitem testar componentes React sem depender dos detalhes de implementação. Essa abordagem facilita a refatoração e também te orienta para as melhores práticas de acessibilidade.',
  },
  {
    id: '10',
    title: 'Node',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/node.png?raw=true",
    category: 'back',
    description: 'Node.js é um software de código aberto, multiplataforma, baseado no interpretador V8 do Google e que permite a execução de códigos JavaScript fora de um navegador web. A principal característica do Node.js é sua arquitetura assíncrona e orientada por eventos.',
  },
  {
    id: '11',
    title: 'MySql',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/mysql.png?raw=true",
    category: 'back',
    description: 'O MySQL é um sistema de gerenciamento de banco de dados, que utiliza a linguagem SQL como interface. É atualmente um dos sistemas de gerenciamento de bancos de dados mais populares da Oracle Corporation, com mais de 10 milhões de instalações pelo mundo. ',
  },
  {
    id: '12',
    title: 'Express',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/exp.png?raw=true",
    category: 'back',
    description: '',
  },
  {
    id: '13',
    title: 'Sequelize',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/sequelize.png?raw=true",
    category: 'back',
    description: '',
  },
  {
    id: '14',
    title: 'JWT',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://raw.githubusercontent.com/kelvynkhrystian/portifolio/8adbb4d1c4c9bb82c85f3bed6454bb3ebf583eb1/src/imgs/skills/jwt.svg",
    category: 'back',
    description: '',
  },
  {
    id: '15',
    title: 'Chai',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/chai.png?raw=true",
    category: 'back',
    description: '',
  },
  {
    id: '16',
    title: 'Mocha',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/mocha.png?raw=true",
    category: 'back',
    description: '',
  },
  {
    id: '17',
    title: 'Sinon',
    subtitle: "Cascading Style Sheets é um mecanismo para adicionar estilos a uma página web",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/sinon.png?raw=true",
    category: 'back',
    description: '',
  },
  {
    id: '18',
    title: 'Linux',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/linux.png?raw=true",
    category: 'ferr',
    description: '',
  },
  {
    id: '19',
    title: 'Git',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/git.png?raw=true",
    category: 'ferr',
    description: '',
  },
  {
    id: '20',
    title: 'Docker',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/docker.png?raw=true",
    category: 'ferr',
    description: '',
  },
  {
    id: '21',
    title: 'Vercel',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/vercel.jpg?raw=true",
    category: 'ferr',
    description: '',
  },
  {
    id: '22',
    title: 'Trello',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/trello.png?raw=true",
    category: 'ferr',
    description: '',
  },
  {
    id: '23',
    title: 'Slack',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/slack.png?raw=true",
    category: 'ferr',
    description: '',
  },
  {
    id: '24',
    title: 'Figma',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/figma.png?raw=true",
    category: 'ferr',
    description: '',
  },
  {
    id: '25',
    title: 'Thunder',
    subtitle: "SO",
    image : "https://github.com/kelvynkhrystian/portifolio/blob/main/src/imgs/skills/thunder.png?raw=true",
    category: 'ferr',
    description: '',
  }
  
]

export default skills;